name: Render Big Tree Map

on:
  schedule:
    - cron: '0 0 1 * *'  # Run at midnight on the 1st day of every month
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'  

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgeos-dev \
            libgdal-dev \
            libproj-dev \
            pandoc

      - name: Install R packages
        run: |
          Rscript -e "install.packages('rmarkdown', dependencies = TRUE)"
          Rscript -e "install.packages('gsheet', dependencies = TRUE)"
          Rscript -e "install.packages('sf', dependencies = TRUE)"
          Rscript -e "install.packages('dplyr', dependencies = TRUE)"
          Rscript -e "install.packages('tidyr', dependencies = TRUE)"
          Rscript -e "install.packages('lubridate', dependencies = TRUE)"
          Rscript -e "install.packages('stringr', dependencies = TRUE)"
          Rscript -e "install.packages('leaflet', dependencies = TRUE)"
          Rscript -e "install.packages('maps', dependencies = TRUE)"
          Rscript -e "install.packages('tigris', dependencies = TRUE)"
          Rscript -e "install.packages('crosstalk', dependencies = TRUE)"

      - name: Verify package installations
        run: |
          Rscript -e "installed.packages()"

      - name: Render R Markdown
        run: |
          Rscript -e "rmarkdown::render('docs/map.Rmd', output_file = 'docs/index.html', output_dir = 'docs')"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./docs
